url: 
baseurl:

# Site settings
title: Dynamics Freelance
email: chinozhang@hotmail.com
description: "Dynamics Freelance, zoekt u een Dynamics AX of Dynamics CRM freelancer? Neem dan contact op met Chino Zhang"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Chino Zhang
  pic: 1
  position: Lead Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: stack-overflow
    url: http://stackoverflow.com/users/276075/chino
  - title: linkedin
    url: https://nl.linkedin.com/in/chinozhang

# Postal address (add as many lines as necessary)
#address:
#  - line: 3481 Melrose Place
#  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty